server:
  port: 9001
spring:
  datasource:
    continue-on-error: true
    password: '1998'
    testWhileIdle: true
    url: jdbc:postgresql://localhost:5432/test2
    username: 'postgres'
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest